/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Controlador.*;
import static Controlador.Controlador.ventana;

/**
 *
 * @author alexb
 */
public class Ventana_1 extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public Ventana_1() {
        initComponents();
        
    }
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ventana1_caja_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Ventana1_nombre_CIUDAD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VENTANA1_ComboBox_GMT = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Ventana1_caja_buscar_nombre = new javax.swing.JTextField();
        Caja1_Bonton_buscar = new javax.swing.JButton();
        Ventana1_boton_agregar = new javax.swing.JButton();
        Ventana1_boton_actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_ciudad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel4.setText("GMT");

        jLabel3.setText("Nombre");

        Caja1_Bonton_buscar.setText("Buscar");
        Caja1_Bonton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja1_Bonton_buscarActionPerformed(evt);
            }
        });

        Ventana1_boton_agregar.setText("Agregar");
        Ventana1_boton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ventana1_boton_agregarActionPerformed(evt);
            }
        });

        Ventana1_boton_actualizar.setText("Actualizar");
        Ventana1_boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ventana1_boton_actualizarActionPerformed(evt);
            }
        });

        Tabla_ciudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ciudadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_ciudad);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(VENTANA1_ComboBox_GMT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Ventana1_nombre_CIUDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ventana1_caja_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ventana1_boton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Ventana1_boton_actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ventana1_caja_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Caja1_Bonton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Ventana1_caja_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ventana1_caja_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Caja1_Bonton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ventana1_nombre_CIUDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(VENTANA1_ComboBox_GMT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ventana1_boton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ventana1_boton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ventana1_boton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ventana1_boton_agregarActionPerformed
       
    }//GEN-LAST:event_Ventana1_boton_agregarActionPerformed

    private void Ventana1_boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ventana1_boton_actualizarActionPerformed

    }//GEN-LAST:event_Ventana1_boton_actualizarActionPerformed

    private void Caja1_Bonton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja1_Bonton_buscarActionPerformed

    }//GEN-LAST:event_Caja1_Bonton_buscarActionPerformed

    
    
    
    
    
    
    
    
    private void Tabla_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ciudadMouseClicked
//       Controlador.Tabla_ciudadMouseClicked(evt);
    }//GEN-LAST:event_Tabla_ciudadMouseClicked

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_1().setVisible(true);
            }
        });
    }

    public JButton getVentana1_boton_agregar() {
        return Ventana1_boton_agregar;
    }
    
    
    DefaultTableModel modelito = new DefaultTableModel();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caja1_Bonton_buscar;
    private javax.swing.JTable Tabla_ciudad;
    private javax.swing.JComboBox<String> VENTANA1_ComboBox_GMT;
    private javax.swing.JButton Ventana1_boton_actualizar;
    private javax.swing.JButton Ventana1_boton_agregar;
    private javax.swing.JTextField Ventana1_caja_ID;
    private javax.swing.JTextField Ventana1_caja_buscar_nombre;
    private javax.swing.JTextField Ventana1_nombre_CIUDAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public DefaultTableModel getModelito() {
        return modelito;
    }

    public void setModelito(DefaultTableModel modelito) {
        this.modelito = modelito;
    }

    public JButton getCaja1_Bonton_buscar() {
        return Caja1_Bonton_buscar;
    }

    public void setCaja1_Bonton_buscar(JButton Caja1_Bonton_buscar) {
        this.Caja1_Bonton_buscar = Caja1_Bonton_buscar;
    }

    public JComboBox<String> getVENTANA1_ComboBox_GMT() {
        return VENTANA1_ComboBox_GMT;
    }

    public void setVENTANA1_ComboBox_GMT(JComboBox<String> VENTANA1_ComboBox_GMT) {
        this.VENTANA1_ComboBox_GMT = VENTANA1_ComboBox_GMT;
    }

    public JTextField getVentana1_caja_ID() {
        return Ventana1_caja_ID;
    }

    public void setVentana1_caja_ID(JTextField Ventana1_caja_ID) {
        this.Ventana1_caja_ID = Ventana1_caja_ID;
    }

    public JTextField getVentana1_caja_buscar_nombre() {
        return Ventana1_caja_buscar_nombre;
    }

    public void setVentana1_caja_buscar_nombre(JTextField Ventana1_caja_buscar_nombre) {
        this.Ventana1_caja_buscar_nombre = Ventana1_caja_buscar_nombre;
    }

    public JTextField getVentana1_nombre_CIUDAD() {
        return Ventana1_nombre_CIUDAD;
    }

    public void setVentana1_nombre_CIUDAD(JTextField Ventana1_nombre_CIUDAD) {
        this.Ventana1_nombre_CIUDAD = Ventana1_nombre_CIUDAD;
    }

    public JTable getTabla_ciudad() {
        return Tabla_ciudad;
    }

    public void setTabla_ciudad(JTable Tabla_ciudad) {
        this.Tabla_ciudad = Tabla_ciudad;
    }

    public JButton getVentana1_boton_actualizar() {
        return Ventana1_boton_actualizar;
    }

 
  

}
